name=ESP32Wiimote
version=0.1.4
author=Daiki Yasuda <karinkuro@gmail.com>
maintainer=Daiki Yasuda <karinkuro@gmail.com>
sentence=Bluetooth Wiimote Library for ESP32
paragraph=Library for connecting Wii Remote (Wiimote) and Nunchuk to ESP32 via Bluetooth Classic. Features button detection, accelerometer data, battery monitoring, and connection status.
category=Communication
url=https://github.com/bigw00d/ESP32Wiimote
architectures=*
includes=ESP32Wiimote.h