// Copyright (c) 2026 ESP32Wiimote contributors
//
// This is licensed under
// - Creative Commons Attribution-NonCommercial 3.0 Unported
// - https://creativecommons.org/licenses/by-nc/3.0/
// - Or see LICENSE.md

#ifndef ESP32WIIMOTE_UTILS_HCI_CODES_H_
#define ESP32WIIMOTE_UTILS_HCI_CODES_H_

#include <stdint.h>

enum class HciStatusCode : uint8_t {
    SUCCESS = 0x00,
    UNKNOWN_HCI_COMMAND = 0x01,
    UNKNOWN_CONNECTION_IDENTIFIER = 0x02,
    HARDWARE_FAILURE = 0x03,
    PAGE_TIMEOUT = 0x04,
    AUTHENTICATION_FAILURE = 0x05,
    PIN_OR_KEY_MISSING = 0x06,
    MEMORY_CAPACITY_EXCEEDED = 0x07,
    CONNECTION_TIMEOUT = 0x08,
    CONNECTION_LIMIT_EXCEEDED = 0x09,
    SYNCHRONOUS_CONNECTION_LIMIT_EXCEEDED = 0x0A,
    CONNECTION_ALREADY_EXISTS = 0x0B,
    COMMAND_DISALLOWED = 0x0C,
    CONNECTION_REJECTED_LIMITED_RESOURCES = 0x0D,
    CONNECTION_REJECTED_SECURITY = 0x0E,
    CONNECTION_REJECTED_BAD_BD_ADDR = 0x0F,
    CONNECTION_ACCEPT_TIMEOUT_EXCEEDED = 0x10,
    UNSUPPORTED_FEATURE_OR_PARAMETER = 0x11,
    INVALID_HCI_COMMAND_PARAMETERS = 0x12,
    REMOTE_USER_TERMINATED_CONNECTION = 0x13,
    REMOTE_DEVICE_TERMINATED_CONNECTION_LOW_RESOURCES = 0x14,
    REMOTE_DEVICE_TERMINATED_CONNECTION_POWER_OFF = 0x15,
    CONNECTION_TERMINATED_BY_LOCAL_HOST = 0x16,
    REPEATED_ATTEMPTS = 0x17,
    PAIRING_NOT_ALLOWED = 0x18,
    UNKNOWN_LMP_PDU = 0x19,
    UNSUPPORTED_REMOTE_FEATURE = 0x1A,
    SCO_OFFSET_REJECTED = 0x1B,
    SCO_INTERVAL_REJECTED = 0x1C,
    SCO_AIR_MODE_REJECTED = 0x1D,
    INVALID_LMP_OR_LL_PARAMETERS = 0x1E,
    UNSPECIFIED_ERROR = 0x1F,
    UNSUPPORTED_LMP_OR_LL_PARAMETER_VALUE = 0x20,
    ROLE_CHANGE_NOT_ALLOWED = 0x21,
    LMP_OR_LL_RESPONSE_TIMEOUT = 0x22,
    LMP_ERROR_TRANSACTION_COLLISION = 0x23,
    LMP_PDU_NOT_ALLOWED = 0x24,
    ENCRYPTION_MODE_NOT_ACCEPTABLE = 0x25,
    LINK_KEY_CANNOT_BE_CHANGED = 0x26,
    REQUESTED_QOS_NOT_SUPPORTED = 0x27,
    INSTANT_PASSED = 0x28,
    PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 0x29,
    DIFFERENT_TRANSACTION_COLLISION = 0x2A,
    QOS_UNACCEPTABLE_PARAMETER = 0x2C,
    QOS_REJECTED = 0x2D,
    CHANNEL_CLASSIFICATION_NOT_SUPPORTED = 0x2E,
    INSUFFICIENT_SECURITY = 0x2F,
    PARAMETER_OUT_OF_MANDATORY_RANGE = 0x30,
    ROLE_SWITCH_PENDING = 0x32,
    RESERVED_SLOT_VIOLATION = 0x34,
    ROLE_SWITCH_FAILED = 0x35,
    EXTENDED_INQUIRY_RESPONSE_TOO_LARGE = 0x36,
    SECURE_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST = 0x37,
    HOST_BUSY_PAIRING = 0x38,
    CONNECTION_REJECTED_NO_SUITABLE_CHANNEL_FOUND = 0x39,
    CONTROLLER_BUSY = 0x3A,
    UNACCEPTABLE_CONNECTION_PARAMETERS = 0x3B,
    ADVERTISING_TIMEOUT = 0x3C,
    CONNECTION_TERMINATED_MIC_FAILURE = 0x3D,
    CONNECTION_FAILED_TO_BE_ESTABLISHED = 0x3E,
    MAC_CONNECTION_FAILED = 0x3F,
};

enum class HciOpcode : uint16_t {
    INQUIRY = 0x0401,
    INQUIRY_CANCEL = 0x0402,
    CREATE_CONNECTION = 0x0405,
    REMOTE_NAME_REQUEST = 0x0419,

    RESET = 0x0C03,
    WRITE_LOCAL_NAME = 0x0C13,
    WRITE_CLASS_OF_DEVICE = 0x0C24,
    WRITE_SCAN_ENABLE = 0x0C1A,

    READ_BD_ADDR = 0x1009,
};

enum class HciEventCode : uint8_t {
    INQUIRY_COMPLETE = 0x01,
    INQUIRY_RESULT = 0x02,
    CONNECTION_COMPLETE = 0x03,
    DISCONNECTION_COMPLETE = 0x05,
    REMOTE_NAME_REQUEST_COMPLETE = 0x07,
    COMMAND_COMPLETE = 0x0E,
    COMMAND_STATUS = 0x0F,
    NUMBER_OF_COMPLETED_PACKETS = 0x13,
};

enum class HciDisconnectionReason : uint8_t {
    AUTHENTICATION_FAILURE = 0x05,
    REMOTE_USER_TERMINATED_CONNECTION = 0x13,
    REMOTE_DEVICE_TERMINATED_CONNECTION_LOW_RESOURCES = 0x14,
    REMOTE_DEVICE_TERMINATED_CONNECTION_POWER_OFF = 0x15,
    CONNECTION_TERMINATED_BY_LOCAL_HOST = 0x16,
    CONNECTION_TIMEOUT = 0x08,
};

const char *hciStatusCodeToString(uint8_t statusCode);
const char *hciOpcodeToString(uint16_t opcode);
const char *hciEventCodeToString(uint8_t eventCode);
const char *hciDisconnectionReasonToString(uint8_t reasonCode);

#endif  // ESP32WIIMOTE_UTILS_HCI_CODES_H_
